Skip migrate check when creating combined database
galaxy.model.tool_shed_install.migrate.check.create_or_verify_database
would never run when creating a combined install database
(https://github.com/galaxyproject/galaxy/blob/bb395a277839465dd490e1cc8c45dd17bddacb23/lib/galaxy/config/__init__.py#L1246)
except when running create_db.sh, which would fail iff sequential
migration was forced with GALAXY_TEST_FORCE_DATABASE_MIGRATION=1, leading to
```
Traceback (most recent call last):
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/migrate/versioning/schema.py", line 50, in load
    data = list(result)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./scripts/create_db.py", line 47, in <module>
    invoke_create()
  File "./scripts/create_db.py", line 39, in invoke_create
    create_install_db(config['db_url'])
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/model/tool_shed_install/migrate/check.py", line 85, in create_or_verify_database
    db_schema = schema.ControlledSchema(engine, migrate_repository)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/migrate/versioning/schema.py", line 33, in __init__
    self.load()
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/migrate/versioning/schema.py", line 54, in load
    exceptions.DatabaseNotControlledError(str(exc)), tb)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/migrate/versioning/schema.py", line 50, in load
    data = list(result)[0]
```
This is because the manual migrations create the tool_shed_repository
table, and so `db_schema = schema.ControlledSchema(engine,
migrate_repository)` fails.