Don't serialize view of item in delete/purge request
This is a breaking change for the API, it is motivated by
https://sentry.galaxyproject.org/share/issue/3970e49a695f4600bcaeae55021555a9/:
```
Message
Unexpected error
Stack Trace

Newest

FileNotFoundError: [Errno 2] No such file or directory: ''
  File "galaxy/datatypes/interval.py", line 1326, in get_estimated_display_viewport
    with open(dataset.get_file_name()) as fh:
```
This is a purge request, which does return the entire detailed response,
including available display applications. We already check that the
dataset isn't purged, but ther celery task often executes between the
check and the deletion.

I don't think it makes sense to return any data at all here,
and there are other endpoints where we simply return 202 or 204,
like purging user file source instanes.